CREATE DATABASE [Population]

USE [Population]

CREATE TABLE Continents(
	Id TINYINT PRIMARY KEY IDENTITY
	,[Name] VARCHAR(30) NOT NULL
);

CREATE TABLE Countries(
	Id SMALLINT PRIMARY KEY IDENTITY
	,[Name] VARCHAR(60) NOT NULL
	,ContinentId TINYINT FOREIGN KEY REFERENCES Continents(Id) NOT NULL
);

CREATE TABLE CapitalCities(
	Id SMALLINT PRIMARY KEY IDENTITY
	,[Name] VARCHAR(60) NOT NULL
	,CountryId SMALLINT FOREIGN KEY REFERENCES Countries(Id) NOT NULL
);

CREATE TABLE Years(
	Id SMALLINT PRIMARY KEY IDENTITY(1950, 1)
	,[Year] SMALLINT NOT NULL
);

CREATE TABLE CountriesByYear(
	Id SMALLINT PRIMARY KEY IDENTITY
	,CountryId SMALLINT FOREIGN KEY REFERENCES Countries(Id) NOT NULL
	,YearId SMALLINT FOREIGN KEY REFERENCES Years(Id) NOT NULL
	,[Population] INT 
	,[TFR] DECIMAL(4, 2)
);

CREATE TABLE CapitalCitiesByYear(
	Id SMALLINT PRIMARY KEY IDENTITY
	,CapitalCityId SMALLINT FOREIGN KEY REFERENCES CapitalCities(Id) NOT NULL
	,YearId SMALLINT FOREIGN KEY REFERENCES Years(Id) NOT NULL
	,[Population] INT 
	,[TFR] DECIMAL(4, 2)
);

