INSERT INTO Continents ([Name]) VALUES
('Europe'),
('North America'),
('South America'),
('Asia'),
('Africa'),
('Australia and Oceania'),
('Antarctica');

INSERT INTO Countries([Name], ContinentId) VALUES
('Afghanistan', 4),
('Albania', 1),
('Algeria', 5),
('Angola', 5),
('Argentina', 3),
('Armenia', 1),
('Australia', 6),
('Austria', 1),
('Azerbaijan', 4),
('Bahamas', 2),
('Bahrain', 4),
('Bangladesh', 4),
('Belarus', 1),
('Belgium', 1),
('Belize', 2),
('Benin', 5),
('Bhutan', 4),
('Bolivia', 3),
('Bosnia & Herzegovina', 1),
('Botswana', 5),
('Brazil', 3),
('Brunei', 4),
('Bulgaria', 1),
('Burkina Faso', 5),
('Burma', 4),
('Burundi', 5),
('Cabo Verde', 5),
('Canada', 2),
('Cambodia', 4),
('Cameron', 5),
('Chad', 5),
('Chile', 3),
('China', 4),
('Colombia', 3),
('Comoros', 5),
('Costa Rica', 2),
('Cote dIvoire', 5),
('Croatia', 1),
('Cuba', 2),
('Cyprus', 1),
('Czech Republic', 1),
('Democratic Republic of the Congo', 5),
('Denmark', 1),
('Djibouti', 5),
('Dominican Republic', 2),
('Ecuador', 3),
('Egypt', 5),
('El Salvador', 2),
('Equatorial Guinea', 5),
('Eritrea', 5),
('Estonia', 1),
('Eswatini', 5),
('Ethiopia', 5),
('Fiji', 6),
('Finland', 1),
('France', 1),
('Gabon', 5),
('Gambia', 5),
('Georgia', 1),
('Germany', 1),
('Ghana', 5),
('Greece', 1),
('Greenland', 2),
('Guatamala', 2),
('Guinea', 5),
('Guinea-Bissau', 5),
('Guyanna', 3),
('Honduras', 2),
('Hungary', 1),
('Iceland', 1),
('India', 4),
('Indonesia', 4),
('Iran', 4),
('Iraq', 4),
('Ireland', 1),
('Israel', 4),
('Italy', 1),
('Jamaica', 2),
('Japan', 4),
('Jordan', 4),
('Kazakhstan', 4),
('Kenya', 5),
('Kosovo', 1),
('Kuwait', 4),
('Kyrgyzstan', 4),
('Laos', 4),
('Latvia', 1),
('Lebanon', 4),
('Lesotho', 5),
('Liberia', 5),
('Libya', 5),
('Lithuania', 1),
('Luxemburg', 1),
('Madagascar', 5),
('Malawi', 5),
('Malaysia', 4),
('Maldives', 4),
('Mali', 5),
('Malta', 1),
('Mauritania', 5),
('Mauritius', 5),
('Mexico', 2),
('Micronesia', 6),
('Moldova', 1),
('Mongolia', 4),
('Montenegro', 1),
('Morocco', 5),
('Mozambique', 5),
('Namibia', 5),
('Nepal', 4),
('Netherlands', 1),
('New Zealand', 6),
('Nicaragua', 2),
('Niger', 5),
('Nigeria', 5),
('North Korea', 4),
('Norway', 1),
('Oman', 4),
('Pakistan', 4),
('Panama', 2),
('Papua New Guinea', 6),
('Paraguay', 3),
('Peru', 3),
('Philippines', 4),
('Poland', 1),
('Portugal', 1),
('Puerto Rico', 2),
('Qatar', 4),
('Republic of the Congo', 2),
('Romania', 1),
('Russia', 1),
('Rwanda', 5),
('Saudi Arabia', 4),
('Senegal', 5),
('Serbia', 1),
('Sierra Leone', 5),
('Singapore', 4),
('Slovakia', 1),
('Slovenia', 1),
('Solomon Islands', 6),
('Somalia', 5),
('South Africa', 5),
('South Korea', 4),
('South Sudan', 5),
('Spain', 1),
('Sri Lanka', 4),
('Sudan', 5),
('Suriname', 3),
('Sweden', 1),
('Switzerland', 1),
('Syria', 4),
('Tajikistan', 4),
('Tanzania', 5),
('Thailand', 4),
('Timor-Leste', 4),
('Togo', 5),
('Trinidad and Tobago', 2),
('Tunisia', 5),
('Turkey', 4),
('Turkmenistan', 4),
('Uganda', 5),
('Ukraine', 1),
('United Arab Emirates', 4),
('United Kingdom', 1),
('United States of America', 2),
('Uruguay', 3),
('Uzbekistan', 4),
('Vanuatu', 6),
('Venezuela', 3),
('Vietnam', 4),
('Yemen', 4),
('Zambia', 5),
('Zimbabwe', 5)

